# Generated by Django 4.1.1 on 2022-09-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('new_pdf', models.FileField(upload_to='new-pdf/')),
            ],
        ),
    ]
