# Generated by Django 4.1.1 on 2022-09-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfGenerator', '0002_alter_pdfgenerator_new_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfgenerator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pdfgenerator',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
